### ISSUE TITLE
unable to resolve "numpy" ans "requests"

### ISSUE THREAD

**Issue by psonntag40** [barneygale/runaway-robot#1]
Im new to programming and wanted to look at some projects. I liked this one. does this work with python3 too?

**Comment by barneygale** [comment]
Hey,

You can use [`pip`](https://pip.pypa.io) to install `numpy` and `requests`. I believe this project works fine with python3.

This project might not be a good intro to programming unless you have a background in something related (such as mathematics) already. I say this because `numpy` is a library you probably shouldn't worry about when you're first picking up programming.

Cheers
